apiVersion: apps/v1
kind: Deployment
metadata:
  # Define the Deployment Name
  name: nginx-deployment
  namespace: dev
  labels:
    app: nginx
spec:
  # Define the Number of Pods
  replicas: 4
  revisionHistoryLimit: 0
  # Define the Selector
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: # Container Details
      - name: nginx
        image: raniasaeed123/nginxprivate:latest # {"$imagepolicy" :"flux-system:podinfo"}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-secret
