apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      
 ----
 
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 1212
  externalTrafficPolicy: Local
  type: LoadBalancer
